name = "sesame-meta"
main = "meta-worker.js"
compatibility_date = "2025-06-09"

routes = [
  { pattern = "sesame.fahrnbach.one", custom_domain = true }
]

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "SESAME_DATA"
bucket_name = "sesame-data"
preview_bucket_name = "sesame-data"
